[package]
authors = ["Wesley Taylor <jamsterwes@gmail.com>"]
name = "supernova"
version = "0.0.1"

[dependencies]
cgmath = "0.16.1"
gl = "0.14.0"
glfw = "0.55.0"
image = "0.19.0"
tobj = "0.1.6"
num = "0.2.0"
rand = "0.5.5"